name: Build UserScript

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get package version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Build script
      run: yarn build
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/TinderExtra.user.js"
        artifactContentType: text/javascript
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.package-version.outputs.current-version }}
        allowUpdates: true
